# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider :hyperv do |v|
        v.vmname  = "restarternator" 
    end

    config.vm.hostname = "restarternator"
    config.vm.network "public_network"
    config.vm.provider "hyperv"
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "./../..", "/vagrant", type: "smb"
    config.vm.provision :shell, path: "./../provision.sh"
    
    # Note that in hyperV, you cannot access a guest via localhost:5100, 
    # use "ip address" to get machine address, it will be available at this
    config.vm.network "forwarded_port", guest: 5100, host: 5100
end